// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateEncryptedNote(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateEncryptedNote'](arg1, arg2, arg3, arg4);
}

export function CreateNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateNote'](arg1, arg2, arg3);
}

export function DecryptNote(arg1, arg2) {
  return window['go']['main']['App']['DecryptNote'](arg1, arg2);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function GetAllNotes() {
  return window['go']['main']['App']['GetAllNotes']();
}

export function GetNoteByID(arg1) {
  return window['go']['main']['App']['GetNoteByID'](arg1);
}

export function UpdateEncryptedNote(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateEncryptedNote'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateNote(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateNote'](arg1, arg2, arg3, arg4);
}
