// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateEncryptedNote(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<models.Note>;

export function CreateNote(arg1:string,arg2:string,arg3:Array<string>):Promise<models.Note>;

export function DecryptNote(arg1:string,arg2:string):Promise<models.Note>;

export function DeleteNote(arg1:string):Promise<void>;

export function GetAllNotes():Promise<Array<models.Note>>;

export function GetNoteByID(arg1:string):Promise<models.Note>;

export function UpdateEncryptedNote(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<models.Note>;

export function UpdateNote(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<models.Note>;
